### ISSUE TITLE
[Feature] When manually searching for episode, add season and episode to search

### ISSUE THREAD

**Issue by shadowwolf899** [lardbit/nefarious#125]
It'd be great if when I try to manually search an episode that the season and episode get appended to the show name. This would help a lot when searching for a show with a long list of episodes. 

Example:
When searching for 'Adventure Time', and I click the magnifying glass to manually search for Season 1 Episode 1, currently the manual search is auto populated with just `Adventure Time`. It'd be great if instead it was auto populated with something along the lines of `Adventure Time S01E01` (maybe the exact formatting could be configurable)

**Comment by lardbit** [comment]
Hey @shadowwolf899,

You're right, it does seem strange that it doens't just populate the search specifically for the episode.  I intentionally chose to do it this way because of the way that torrents are named.  For instance, some results will match **Adventure Time S01E01** while some would only match **Adventure Time Season 1**.  If nefarious defaulted to one or the other, then you'd miss valid results.  I thought it was less confusing to search the more general **Adventure Time** and then let the user sort through the results using the filter input.  Thoughts?

**Comment by lardbit** [comment]
Explanation provided, closed due to inactivity.
