### ISSUE TITLE
Feature Request - Docker config support

### ISSUE THREAD

**Issue by RicardoVelaC** [lardbit/nefarious#13]
Add support to docker image to make config persists after rebuild image. 
With docker parameters or mounting a config file

**Comment by lardbit** [comment]
Sorry I wasn't getting notifications for new issues.  Just seeing this.  

Can you elaborate on this request?  Do you want your nefarious application settings to persist after rebuilding image?  The `docker-compose.yml` file uses named volume mounts which will persist even after rebuilding the image.

**Comment by lardbit** [comment]
If you're using the default `docker-compose.yml` you shouldn't have to rebuild the image because it'll be automatically updating itself on every commit into master (via https://github.com/containrrr/watchtower).  Plus, since it's using named docker volumes, when you bring the nefarious container back up i'll maintain whatever settings you already had.

However, if you're running the docker containers manually, you'd just need to reference the existing named volume you initially created it with.

**Comment by RicardoVelaC** [comment]
> If you're using the default docker-compose.yml you shouldn't have to rebuild the image because it'll be automatically updating itself on every commit into master (via https://github.com/containrrr/watchtower). 

I know it. But I use Docker for Synology I can auto update images (via https://github.com/containrrr/watchtower) but Synology Docker doesn´t support docker-compose 😣

> Plus, since it's using named docker volumes, when you bring the nefarious container back up it'll maintain whatever settings you already had.

Since when nefarious support mount volumes? It's documented in README.md?

I think the best for an universal scenario, it's put al configuration in a config file and mount it via docker volume

**Comment by lardbit** [comment]
> Since when nefarious support mount volumes? It's documented in README.md?

Well, I guess it supports named volumes out of the box via the `docker-compose.yml` file.  However, it'll work similarly with named volumes with something like:

     docker run -d \
        --rm \
        --name nefarious-app \
        -e DATABASE_URL=sqlite:////nefarious-db/db.sqlite3 \
        -v nefarious-db:/nefarious-db \
        -p 8000:80 \
        lardbit/nefarious

Then, you can use nefarious, define settings, download things, etc.  When you want to update nefarious, or just decide to stop & remove the container for whatever reason, it'll maintain all the data since you defined the named volume **nefarious-db**.

Example:

Stop and remove the container.

    docker stop nefarious-app

Update nefarious:

    docker pull lardbit/nefarious

Then you can re-run the previous `docker run` command and it'll use the data from the named volume `nefarious-db`.  Make sure the *celery* app uses the same named volume.

**Comment by RicardoVelaC** [comment]
Oh, interesting... I'll try to config it

**Comment by lardbit** [comment]
I believe the named volume suggestion is a valid solution. Closing.
