### ISSUE TITLE
Downloads non watched shows/movies

### ISSUE THREAD

**Issue by panmau** [lardbit/nefarious#154]
Since the [last update](https://github.com/lardbit/nefarious/commit/9eaac1c154a629068b9a260e4a3a3e6c6ae8893b) nefarious downloads shows/movies that I have already downloaded and most of them I don't have on my watchlist anymore.

These downloads aren't put into the movie or tv folder but instead directly into the completed folder. Additionally they don't trigger notifications. 

Unfortunately I didn't figure out yet how this issue can be reliably reproduced for a different show/movie.
Let me know if you need more info! I have the feeling that some output from the database would be helpful to find the root cause of this, but I would need some info first on where to exactly look and how I can access it.

**Comment by lardbit** [comment]
You know what, I've seen this behavior before too.  I concluded, at least in my scenario, that the issue was triggered when I restarted Transmission and when it restarted it began re-downloading torrents that were very old and already complete.  I unfortunately can't figure out when/why it happens, but I had to manually log into Transmission and delete those torrents.

I am pretty confident that nefarious isn't the instigator requesting to re-download these movies/shows and that it's a transmission restart/corruption issue, but, I also can't reproduce it.  

Sorry that's not much help here.  Let me know if you come across any clues on your end.

**Comment by panmau** [comment]
Thanks for your answer.

The thing is though that I already logged into transmission and deleted these torrents. But every time I delete the downloaded files, the torrents are added again.
This seems to me like nefarious triggers the download again or am I missing something about how this works?

As this only happened after the linked recent commit I think it could maybe have to do with the change regarding the null values but I could be completely wrong here.

**Comment by lardbit** [comment]
I don't believe that nefarious commit would be the culprit, but hey anything's possible.  I have personally experienced this re-downloading behavior, a couple times actually, in the last few months.  My solution, not a great one, was to delete transmission's `resume` & `torrents` folder which is inside of `HOST_DOWNLOAD_PATH` / **transmission-home/**.  Mine is filled with old torrents and I think in some bad state/scenario transmission picks those back up incorrectly.

The reason I don't believe it's nefarious is because nefarious always moves the downloads to the right location afterwards, and will trigger notifications.  Also, it would only trigger downloads if they were never actually downloaded. 

Would you mind testing this hypothesis?

**Comment by lardbit** [comment]
Someone here experienced it as well. Never confirmed the issue though.

https://www.reddit.com/r/torrents/comments/k9ypbz/transmission_readds_and_redownloads_old_torrents/?utm_medium=android_app&utm_source=share

**Comment by panmau** [comment]
After applying the workaround I didn't have that behaviour anymore. This 'fix' is fine for me right now so I will close the issue. Thanks.
