### ISSUE TITLE
File deleted when I stop watching

### ISSUE THREAD

**Issue by canepan** [lardbit/nefarious#201]
Hi, I noticed what might look like a feature, but is annoyng for me.
When I stop watching a movie, it gets also deleted from my library.
Is it possible to keep it, or to have an option for that?
I don't want a long list of watched movies, since I want to keep the list clean, but I like to keep some of them.

Thank you

**Comment by lardbit** [comment]
It's definitely a feature. Do you manually delete movies when you're done with them to maintain hard drive space? Nefarious just tries to be in sync with what you have on disk. 

The only workaround, currently, would be to remove the torrent from transmission before you "stop watching" and nefarious won't be able to delete anything since it does it through transmission.

**Comment by canepan** [comment]
I'm not using Nefarious to watch movies or to maintain my library, so I didn't expect this.
This also means if I remove a movie outside of Nefarious, it will detect and re-download?

**Comment by lardbit** [comment]
No, if you remove a movie outside of nefarious, it won't try to re-download it.
