### ISSUE TITLE
Problem when searching in the trackers

### ISSUE THREAD

**Issue by sakulsol** [lardbit/nefarious#221]
good morning, it would be possible that when performing a search in automatic mode the program omitted the : , since many trackers do not name the uploads with the :

thanks in advance.

**Comment by lardbit** [comment]
nefarious sends the search term using the full title (including colon), but it will match results without the colon.  There's a [unit test](https://github.com/lardbit/nefarious/blob/2f1bb03ed331f118f4e55bed9fd33d6444c07c52/src/nefarious/tests/test_match_movie.py#L22) that has a colon in the title which tests for that.

I wouldn't want to omit the colon before sending to the tracker since we can't guarantee which trackers omit the colon vs include it.  We just have to hope their search mechanisms work well enough.

**Comment by lardbit** [comment]
Closed due to inactivity.
