### ISSUE TITLE
[Feature] Avoid the colons in comparations

### ISSUE THREAD

**Issue by JorTurFer** [lardbit/nefarious#90]
There are a lot of movies (in spanish) whose use colon in the movie name. For example `Spider-Man: Lejos de casa`. Thing this is that a lot of uploaders in trackers don't write the name with the colon. Following the previous sample:
![image](https://user-images.githubusercontent.com/36899226/108601373-877ada80-739c-11eb-93a7-5775b4b01e98.png)

The point here is I think that a simple replace of the colon in the string before the comparation would handle good a big part of them. I am not sure but I suppose it :)

You are doing a very good job with this project! Thanks for all :)

**Comment by lardbit** [comment]
@JorTurFer, nefarious *should* be ignoring the colon when comparing the results.  I wrote some tests that include that scenario. 
 See https://github.com/lardbit/nefarious/blob/master/src/nefarious/tests/test_match_movie.py#L22.  

It matches the torrent `Thor: The Dark World 2013` to the movie title `Thor The Dark World`.

Are you seeing nefarious skip valid matches because of the colon? Can you send me your **background logs**?  There's a button on the settings page.  Right click and save and then post back.

**Comment by JorTurFer** [comment]
I will test again ASAP and I will paste the log

**Comment by JorTurFer** [comment]
Okey,
Sorry @lardbit , I am wrong, nefarious is working correctly . It does the comparation well. The problem is that jackett doesn't return the torrents without colon if the request contains colon. 
Sorry for open the issue :(

**Comment by lardbit** [comment]
No worries.  I suppose nefarious **could** always omit the colon when submitting the query to jackett.  I'm not sure that's the right answer.  It just came to mind.

**Comment by JorTurFer** [comment]
I am not sure if it is the correct solution :( The thing here is that the uploaders should use the correct name but that is not the reality... Who should handle it? Nefarious? Jackett? Nobody? I haven't got the answer... 
Could be an option that you enabler or disable using the admin page maybe?

**Comment by lardbit** [comment]
yeah, you're right.  It's tricky.  The whole internationalization issue is tricky.  That's why I haven't spent too much time on it because it's quite involved to handle everything correctly.
